# Generated by Django 6.0.3 on 2026-03-30 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chatatendente", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaDeChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cliente_nome", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aguardando", "Aguardando Atendente"),
                            ("ativo", "Em Atendimento"),
                            ("encerrado", "Encerrado"),
                        ],
                        default="aguardando",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "atendente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="salas",
                        to="chatatendente.atendente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mensagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "remetente_atendente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chatatendente.atendente",
                    ),
                ),
                (
                    "sala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens",
                        to="chatconsumidor.saladechat",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
    ]
