# Generated by Django 6.0.3 on 2026-03-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatconsumidor", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mensagem",
            options={
                "ordering": ["timestamp"],
                "verbose_name": "Mensagem",
                "verbose_name_plural": "Mensagens",
            },
        ),
        migrations.AlterModelOptions(
            name="saladechat",
            options={"verbose_name": "Conversa", "verbose_name_plural": "Conversas"},
        ),
        migrations.AddField(
            model_name="saladechat",
            name="protocolo",
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
