# Generated by Django 6.0.3 on 2026-04-01 16:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "chatconsumidor",
            "0002_alter_mensagem_options_alter_saladechat_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="saladechat",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
