# Generated by Django 6.0.3 on 2026-04-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatconsumidor", "0003_alter_saladechat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="saladechat",
            name="encerrado_por",
            field=models.CharField(
                blank=True,
                choices=[
                    ("atendente", "Atendente"),
                    ("consumidor", "Consumidor"),
                    ("rede_atendente", "Falha de Rede (Atendente)"),
                    ("rede_consumidor", "Falha de Rede (Consumidor)"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
