# Generated by Django 6.0.3 on 2026-04-14 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatconsumidor", "0004_saladechat_encerrado_por"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fila",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="saladechat",
            name="ultima_atividade",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="saladechat",
            name="cpf",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="salas",
                to="chatconsumidor.fila",
            ),
        ),
    ]
