# Generated by Django 6.0.3 on 2026-04-14 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatconsumidor", "0005_fila_saladechat_ultima_atividade_saladechat_cpf"),
    ]

    operations = [
        migrations.AddField(
            model_name="saladechat",
            name="fila",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="salas",
                to="chatconsumidor.fila",
            ),
        ),
        migrations.AlterField(
            model_name="saladechat",
            name="cpf",
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True),
        ),
    ]
