# Generated by Django 6.0.3 on 2026-04-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatconsumidor", "0006_saladechat_fila_alter_saladechat_cpf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saladechat",
            name="encerrado_por",
        ),
        migrations.AddField(
            model_name="fila",
            name="is_principal",
            field=models.BooleanField(default=False, verbose_name="Fila Principal"),
        ),
        migrations.AlterField(
            model_name="saladechat",
            name="status",
            field=models.CharField(
                choices=[
                    ("aguardando", "Aguardando"),
                    ("ativo", "Ativo"),
                    ("encerrado", "Encerrado"),
                ],
                default="aguardando",
                max_length=20,
            ),
        ),
    ]
