# Generated by Django 6.0.3 on 2026-04-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "chatconsumidor",
            "0007_remove_saladechat_encerrado_por_fila_is_principal_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="mensagem",
            name="ai_metadata",
            field=models.JSONField(
                blank=True,
                help_text="Armazena o raciocínio da IA, intenção, trechos usados da base de conhecimento e tokens.",
                null=True,
            ),
        ),
    ]
