# Generated by Django 6.0.3 on 2026-04-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Ex: Bot de Vendas Agressivo", max_length=50
                    ),
                ),
                (
                    "provedor",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI (ChatGPT)"),
                            ("gemini", "Google Gemini"),
                        ],
                        default="openai",
                        max_length=20,
                    ),
                ),
                ("api_key", models.CharField(max_length=255)),
                (
                    "system_prompt",
                    models.TextField(
                        default="Você é um assistente prestativo.",
                        help_text="A personalidade e regras da IA",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Ativo?"),
                ),
            ],
            options={
                "verbose_name": "Configuração de IA",
                "verbose_name_plural": "Configurações de IA",
            },
        ),
    ]
