# Generated by Django 5.1.15 on 2026-04-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoia',
            name='modelo',
            field=models.CharField(default='gpt-4o-mini', help_text="Digite o nome exato da API. Dicas: 'gpt-4o', 'gpt-4o-mini', 'gemini-2.5-flash', 'gemini-1.5-pro', 'claude-3-5-sonnet-20241022'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='configuracaoia',
            name='provedor',
            field=models.CharField(choices=[('openai', 'OpenAI (ChatGPT)'), ('gemini', 'Google Gemini'), ('claude', 'Anthropic (Claude)')], default='openai', max_length=20),
        ),
    ]
