# Generated by Django 5.1.15 on 2026-04-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatai', '0002_configuracaoia_modelo_alter_configuracaoia_provedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoia',
            name='token_telecontrol',
            field=models.CharField(blank=True, help_text='Token da API Telecontrol (access-application-key)', max_length=255, null=True),
        ),
    ]
