# Generated by Django 5.1.15 on 2026-04-19 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatai', '0003_configuracaoia_token_telecontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Consulta de OS Telecontrol', max_length=100)),
                ('identificador', models.SlugField(help_text="ID usado no código para buscar esta API. Ex: 'telecontrol_os'", unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('url_base', models.CharField(help_text='URL completa. Use chaves para variáveis, ex: https://api.com/os/{cpf}', max_length=255)),
                ('metodo', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT')], default='GET', max_length=10)),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Formato JSON. Ex: {"access-env": "PRODUCTION", "access-application-key": "SEU_TOKEN"}')),
            ],
            options={
                'verbose_name': 'API Externa',
                'verbose_name_plural': 'APIs Externas',
            },
        ),
        migrations.RemoveField(
            model_name='configuracaoia',
            name='token_telecontrol',
        ),
        migrations.AddField(
            model_name='configuracaoia',
            name='api_os_vinculada',
            field=models.ForeignKey(blank=True, help_text='Selecione qual API Externa esta IA deve usar para consultar Ordens de Serviço pelo CPF.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatai.apiexterna', verbose_name='API de Consulta de OS'),
        ),
    ]
