# Generated by Django 5.1.15 on 2026-04-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatai', '0004_apiexterna_remove_configuracaoia_token_telecontrol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoia',
            name='prompt_andamento',
            field=models.TextField(default='Atendendo cliente: {nome}. Siga as diretrizes da AIWA.\nCaso tenha passado alguma instrução de reset informe que o procedimento pode levar alguns minutos e que este chat pode ser finalizado dentro de 3 minutos de atividade. Caso a conexão atual caia, só retornar e informar o mesmo numero de CPF que continuaremos com o atendimento.', help_text='Use {nome} para injetar o nome do cliente.', verbose_name='Instrução (Chat em Andamento)'),
        ),
        migrations.AddField(
            model_name='configuracaoia',
            name='prompt_raciocinio',
            field=models.TextField(default='\n\n--- FORMATO OBRIGATÓRIO DE RESPOSTA ---\nEm TODAS as suas mensagens, você DEVE estruturar sua resposta EXATAMENTE desta forma:\n\n<raciocinio>\nEscreva sua análise do contexto e planejamento aqui.\n</raciocinio>\nEscreva a mensagem final que o cliente vai ler aqui. (NUNCA coloque a mensagem do cliente dentro da tag de raciocínio).', help_text='Instrução fixa que obriga a IA a pensar antes de responder.', verbose_name='Regra de Raciocínio (Obrigatório)'),
        ),
        migrations.AddField(
            model_name='configuracaoia',
            name='prompt_saudacao_nova',
            field=models.TextField(default="O número do protocolo DESTA nova sessão é: {protocolo}. O cliente informou no formulário que se chama '{nome}'.\n\nEste é um CLIENTE NOVO. Dê as boas-vindas à AIWA, informe o número do protocolo dele e pergunte como você pode ajudá-lo hoje.", help_text='Use {protocolo} e {nome} para injetar os dados dinâmicos.', verbose_name='Saudação (Novo Cliente)'),
        ),
        migrations.AddField(
            model_name='configuracaoia',
            name='prompt_saudacao_retorno',
            field=models.TextField(default="O número do protocolo DESTA nova sessão é: {protocolo}. O cliente informou no formulário que se chama '{nome}'.\n\nEste cliente JÁ TEM HISTÓRICO (leia as mensagens anteriores). Faça uma saudação de retorno contextualizada, informe o novo protocolo e pergunte se ele quer dar continuidade ao caso anterior.", help_text='Use {protocolo} e {nome} para injetar os dados dinâmicos.', verbose_name='Saudação (Cliente Retornando)'),
        ),
    ]
