# Generated by Django 5.1.15 on 2026-04-19 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatai', '0006_configuracaoia_prompt_contexto_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoia',
            name='api_protocolo_vinculada',
            field=models.ForeignKey(blank=True, help_text='Selecione qual API Externa esta IA deve usar para consultar os Protocolos do cliente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_protocolo', to='chatai.apiexterna', verbose_name='API de Consulta de Protocolos'),
        ),
        migrations.AddField(
            model_name='configuracaoia',
            name='prompt_contexto_protocolo',
            field=models.TextField(default='\n\n--- INFORMAÇÕES DO SISTEMA (PROTOCOLOS ANTERIORES) ---\nO sistema localizou os seguintes protocolos atrelados a este CPF:\n{lista_protocolos}\n\nINSTRUÇÃO: Caso o cliente questione sobre atendimentos ou protocolos anteriores, utilize as informações acima para atualizar o status do caso dele de forma resumida e prestativa.', help_text='Instrução injetada apenas quando o cliente possui protocolos válidos. Use a variável {lista_protocolos}.', verbose_name='Instrução de Protocolos (Telecontrol)'),
        ),
        migrations.AlterField(
            model_name='configuracaoia',
            name='api_os_vinculada',
            field=models.ForeignKey(blank=True, help_text='Selecione qual API Externa esta IA deve usar para consultar Ordens de Serviço pelo CPF.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_os', to='chatai.apiexterna', verbose_name='API de Consulta de OS'),
        ),
        migrations.AlterField(
            model_name='configuracaoia',
            name='prompt_contexto_os',
            field=models.TextField(default="\n\n--- INFORMAÇÕES DO SISTEMA (API TELECONTROL / ORDENS DE SERVIÇO) ---\nO sistema localizou as seguintes Ordens de Serviço (OS) da marca AIWA atreladas ao CPF deste cliente:\n{lista_os}\n\nINSTRUÇÃO OBRIGATÓRIA SOBRE AS OS: Analise as informações acima. Se for a sua primeira mensagem e houverem Ordens de Serviço, você DEVE informar o cliente proativamente sobre o histórico de seus equipamentos. Formate a sua resposta OBRIGATORIAMENTE usando tópicos (bullet points) e destacando o número da OS e o modelo em negrito, por exemplo: '* **OS 12345 (Modelo XYZ):** O status atual é...'.\nSe o produto estiver com status 'Aguardando Retirada' e o Tipo de Atendimento for igual a 'Atendimento Domicílio', Informe que o produto será devolvido em breve e o agendamento de devolução deve ser feito diretamente com a Assistencia.\nSe o produto estiver com status 'Aguardando Retirada' e o Tipo de Atendimento for igual a 'Atendimento Balcao', informe que o produto está pronto e pode ser retirado na assistencia. Se houver mais de uma OS de mesmo Produto e Numero de Serie informe apenas a ultima OS, a menos que o consumidor informe sobre a outra, aja com naturalidade.\nCaso o consumidor pergunte o que foi feito em seu produto, informe que voce não tem acesso as informacões tecnicas e finalize a mensagem perguntando como pode ajudá-lo hoje baseando-se nesses status.", help_text='Instrução injetada apenas quando o cliente possui OSs válidas. Use a variável {lista_os}.', verbose_name='Instrução de Ordens de Serviço'),
        ),
    ]
