# Generated by Django 5.1.15 on 2026-04-24 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatai', '0007_configuracaoia_api_protocolo_vinculada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoia',
            name='api_rede_vinculada',
            field=models.ForeignKey(blank=True, help_text='API para consulta de postos por CEP e Linha.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_rede', to='chatai.apiexterna', verbose_name='API de Rede Autorizada'),
        ),
        migrations.AddField(
            model_name='configuracaoia',
            name='prompt_contexto_rede',
            field=models.TextField(default='\n\n--- POSTOS AUTORIZADOS LOCALIZADOS ---\n{lista_postos}\n\nINSTRUÇÃO: Formate os endereços acima de forma amigável, destacando Nome e Telefone. Se a lista estiver vazia, peça para o cliente tentar outro CEP ou pergunte se quer falar com um humano.', help_text='Instrução injetada quando o cliente retorna o CEP do formulário.', verbose_name='Instrução de Rede Autorizada'),
        ),
        migrations.AlterField(
            model_name='apiexterna',
            name='headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='apiexterna',
            name='identificador',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='apiexterna',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='apiexterna',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='apiexterna',
            name='url_base',
            field=models.CharField(help_text='Ex: https://api.com/cep/{cep}/linha/{linha}', max_length=255),
        ),
        migrations.AlterField(
            model_name='configuracaoia',
            name='api_os_vinculada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_os', to='chatai.apiexterna', verbose_name='API de Consulta de OS'),
        ),
        migrations.AlterField(
            model_name='configuracaoia',
            name='api_protocolo_vinculada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_protocolo', to='chatai.apiexterna', verbose_name='API de Consulta de Protocolos'),
        ),
        migrations.AlterField(
            model_name='configuracaoia',
            name='prompt_andamento',
            field=models.TextField(default='Atendendo cliente: {nome}.', verbose_name='Instrução (Chat em Andamento)'),
        ),
        migrations.AlterField(
            model_name='configuracaoia',
            name='prompt_contexto_os',
            field=models.TextField(default='\n\n--- OS LOCALIZADAS ---\n{lista_os}', verbose_name='Instrução de Ordens de Serviço'),
        ),
        migrations.AlterField(
            model_name='configuracaoia',
            name='prompt_contexto_protocolo',
            field=models.TextField(default='\n\n--- PROTOCOLOS LOCALIZADOS ---\n{lista_protocolos}', verbose_name='Instrução de Protocolos (Telecontrol)'),
        ),
        migrations.AlterField(
            model_name='configuracaoia',
            name='prompt_raciocinio',
            field=models.TextField(default='\n\n<raciocinio>\nAnálise...\n</raciocinio>\nResposta...', verbose_name='Regra de Raciocínio (Obrigatório)'),
        ),
        migrations.AlterField(
            model_name='configuracaoia',
            name='prompt_saudacao_nova',
            field=models.TextField(default="O número do protocolo DESTA nova sessão é: {protocolo}. O cliente informou no formulário que se chama '{nome}'.\n\nEste é um CLIENTE NOVO. Dê as boas-vindas à AIWA.", verbose_name='Saudação (Novo Cliente)'),
        ),
        migrations.AlterField(
            model_name='configuracaoia',
            name='prompt_saudacao_retorno',
            field=models.TextField(default="O número do protocolo DESTA nova sessão é: {protocolo}. O cliente informou no formulário que se chama '{nome}'.\n\nEste cliente JÁ TEM HISTÓRICO.", verbose_name='Saudação (Cliente Retornando)'),
        ),
    ]
