# Generated by Django 5.1.15 on 2026-04-25 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatai', '0008_configuracaoia_api_rede_vinculada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaoia',
            name='api_rede_vinculada',
        ),
        migrations.RemoveField(
            model_name='configuracaoia',
            name='prompt_contexto_rede',
        ),
        migrations.AlterField(
            model_name='apiexterna',
            name='headers',
            field=models.JSONField(blank=True, default=dict, help_text='Formato JSON. Ex: {"access-env": "PRODUCTION", "access-application-key": "SEU_TOKEN"}'),
        ),
        migrations.AlterField(
            model_name='apiexterna',
            name='identificador',
            field=models.SlugField(help_text="ID usado no código para buscar esta API. Ex: 'telecontrol_os'", unique=True),
        ),
        migrations.AlterField(
            model_name='apiexterna',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='apiexterna',
            name='nome',
            field=models.CharField(help_text='Ex: Consulta de OS Telecontrol', max_length=100),
        ),
        migrations.AlterField(
            model_name='apiexterna',
            name='url_base',
            field=models.CharField(help_text='URL completa. Use chaves para variáveis, ex: https://api.com/os/{cpf}', max_length=255),
        ),
        migrations.AlterField(
            model_name='configuracaoia',
            name='api_os_vinculada',
            field=models.ForeignKey(blank=True, help_text='Selecione qual API Externa esta IA deve usar para consultar Ordens de Serviço pelo CPF.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_os', to='chatai.apiexterna', verbose_name='API de Consulta de OS'),
        ),
        migrations.AlterField(
            model_name='configuracaoia',
            name='api_protocolo_vinculada',
            field=models.ForeignKey(blank=True, help_text='Selecione qual API Externa esta IA deve usar para consultar os Protocolos do cliente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_protocolo', to='chatai.apiexterna', verbose_name='API de Consulta de Protocolos'),
        ),
        migrations.AlterField(
            model_name='configuracaoia',
            name='prompt_andamento',
            field=models.TextField(default='Atendendo cliente: {nome}. Siga as diretrizes da AIWA.\nCaso tenha passado alguma instrução de reset informe que o procedimento pode levar alguns minutos e que este chat pode ser finalizado dentro de 3 minutos de atividade. Caso a conexão atual caia, só retornar e informar o mesmo numero de CPF que continuaremos com o atendimento.', help_text='Use {nome} para injetar o nome do cliente.', verbose_name='Instrução (Chat em Andamento)'),
        ),
        migrations.AlterField(
            model_name='configuracaoia',
            name='prompt_contexto_os',
            field=models.TextField(default="\n\n--- INFORMAÇÕES DO SISTEMA (API TELECONTROL / ORDENS DE SERVIÇO) ---\nO sistema localizou as seguintes Ordens de Serviço (OS) da marca AIWA atreladas ao CPF deste cliente:\n{lista_os}\n\nINSTRUÇÃO OBRIGATÓRIA SOBRE AS OS: Analise as informações acima. Se for a sua primeira mensagem e houverem Ordens de Serviço, você DEVE informar o cliente proativamente sobre o histórico de seus equipamentos. Formate a sua resposta OBRIGATORIAMENTE usando tópicos (bullet points) e destacando o número da OS e o modelo em negrito, por exemplo: '* **OS 12345 (Modelo XYZ):** O status atual é...'.\nSe o produto estiver com status 'Aguardando Retirada' e o Tipo de Atendimento for igual a 'Atendimento Domicílio', Informe que o produto será devolvido em breve e o agendamento de devolução deve ser feito diretamente com a Assistencia.\nSe o produto estiver com status 'Aguardando Retirada' e o Tipo de Atendimento for igual a 'Atendimento Balcao', informe que o produto está pronto e pode ser retirado na assistencia. Se houver mais de uma OS de mesmo Produto e Numero de Serie informe apenas a ultima OS, a menos que o consumidor informe sobre a outra, aja com naturalidade.\nCaso o consumidor pergunte o que foi feito em seu produto, informe que voce não tem acesso as informacões tecnicas e finalize a mensagem perguntando como pode ajudá-lo hoje baseando-se nesses status.", help_text='Instrução injetada apenas quando o cliente possui OSs válidas. Use a variável {lista_os}.', verbose_name='Instrução de Ordens de Serviço'),
        ),
        migrations.AlterField(
            model_name='configuracaoia',
            name='prompt_contexto_protocolo',
            field=models.TextField(default='\n\n--- INFORMAÇÕES DO SISTEMA (PROTOCOLOS ANTERIORES) ---\nO sistema localizou os seguintes protocolos atrelados a este CPF:\n{lista_protocolos}\n\nINSTRUÇÃO: Caso o cliente questione sobre atendimentos ou protocolos anteriores, utilize as informações acima para atualizar o status do caso dele de forma resumida e prestativa.', help_text='Instrução injetada apenas quando o cliente possui protocolos válidos. Use a variável {lista_protocolos}.', verbose_name='Instrução de Protocolos (Telecontrol)'),
        ),
        migrations.AlterField(
            model_name='configuracaoia',
            name='prompt_raciocinio',
            field=models.TextField(default='\n\n--- FORMATO OBRIGATÓRIO DE RESPOSTA ---\nEm TODAS as suas mensagens, você DEVE estruturar sua resposta EXATAMENTE desta forma:\n\n<raciocinio>\nEscreva sua análise do contexto e planejamento aqui.\n</raciocinio>\nEscreva a mensagem final que o cliente vai ler aqui. (NUNCA coloque a mensagem do cliente dentro da tag de raciocínio).', help_text='Instrução fixa que obriga a IA a pensar antes de responder.', verbose_name='Regra de Raciocínio (Obrigatório)'),
        ),
        migrations.AlterField(
            model_name='configuracaoia',
            name='prompt_saudacao_nova',
            field=models.TextField(default="O número do protocolo DESTA nova sessão é: {protocolo}. O cliente informou no formulário que se chama '{nome}'.\n\nEste é um CLIENTE NOVO. Dê as boas-vindas à AIWA, informe o número do protocolo dele e pergunte como você pode ajudá-lo hoje.", help_text='Use {protocolo} e {nome} para injetar os dados dinâmicos.', verbose_name='Saudação (Novo Cliente)'),
        ),
        migrations.AlterField(
            model_name='configuracaoia',
            name='prompt_saudacao_retorno',
            field=models.TextField(default="O número do protocolo DESTA nova sessão é: {protocolo}. O cliente informou no formulário que se chama '{nome}'.\n\nEste cliente JÁ TEM HISTÓRICO (leia as mensagens anteriores). Faça uma saudação de retorno contextualizada, informe o novo protocolo e pergunte se ele quer dar continuidade ao caso anterior.", help_text='Use {protocolo} e {nome} para injetar os dados dinâmicos.', verbose_name='Saudação (Cliente Retornando)'),
        ),
    ]
