# Generated by Django 5.1.15 on 2026-04-26 00:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatai', '0009_remove_configuracaoia_api_rede_vinculada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseConhecimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Ex: Regras de Garantia de TVs, Saudação Inicial, etc.', max_length=200)),
                ('conteudo', models.TextField(help_text='O fragmento de texto com o conhecimento que a IA deve aprender.')),
                ('ativo', models.BooleanField(default=True, help_text='Se desmarcado, a IA não usará este texto.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Base de Conhecimento',
                'verbose_name_plural': 'Bases de Conhecimento',
                'ordering': ['-atualizado_em'],
            },
        ),
    ]
