# Generated by Django 5.1.15 on 2026-04-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatai', '0010_baseconhecimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoia',
            name='prompt_orquestrador',
            field=models.TextField(default='Você é o Orquestrador de Ferramentas da AIWA.\nSua única função é ler a mensagem do usuário e decidir quais sistemas consultar.\n\nSistemas disponíveis:\n- "base_conhecimento": Use para dúvidas sobre produtos, como fazer algo, regras de garantia, campanhas ou qualquer pergunta informativa.\n- "ordens_servico": Use APENAS se o cliente perguntar sobre o status de um conserto, assistência técnica ou OS.\n- "protocolos": Use APENAS se o cliente mencionar que já tem um protocolo anterior.\n\nRetorne OBRIGATORIAMENTE um JSON válido com a lista de sistemas a consultar. Exemplo:\n{"sistemas": ["base_conhecimento"]}\nSe for apenas um cumprimento ("Oi", "Bom dia"), retorne: {"sistemas": []}.', help_text="Instruções para o 'Supervisor' decidir quais bancos de dados acionar antes de responder."),
        ),
    ]
